/**
 * Concept registry for Peh's teaching layer.
 *
 * Every concept the teaching system can explain is registered here.
 * Each concept has a plain-language definition, beginner explanation,
 * examples, and connections to related concepts.
 */

import type { TeacherConcept } from "./types";

export const TEACHER_CONCEPTS: readonly TeacherConcept[] = [
  {
    id: "ai",
    title: "Artificial Intelligence (AI)",
    plainLanguageDefinition: "Software that can process language, images, or data and produce useful responses.",
    beginnerExplanation: "AI is software that can read your text and write a response. It is not magic and it is not thinking — it is a program that has learned patterns from lots of text.",
    examples: ["A chatbot that answers your questions", "A program that summarizes a long document"],
    relatedConcepts: ["model", "prompt", "response"],
    prerequisiteConcepts: [],
    commonMisunderstandings: [
      "AI is not sentient or conscious",
      "AI does not always give correct answers",
      "AI does not understand things the way humans do",
    ],
    checkYourUnderstandingQuestions: ["What does AI actually do with your text?"],
    linkedDocs: ["docs/teacher-kb/01-what-is-ai.md"],
  },
  {
    id: "model",
    title: "Model",
    plainLanguageDefinition: "The trained program that reads your input and generates a response.",
    beginnerExplanation: "A model is like a very large pattern-matching program. It was trained on lots of text and learned how to continue conversations, answer questions, and write content. Different models have different strengths and sizes.",
    examples: ["llama3.2 running on your computer via Ollama", "GPT-4 running on OpenAI's servers"],
    relatedConcepts: ["local_model", "cloud_model", "token", "context_window"],
    prerequisiteConcepts: ["ai"],
    commonMisunderstandings: [
      "A model is not the same as an app — Peh uses a model, but Peh is the app",
      "Bigger models are not always better for every task",
    ],
    checkYourUnderstandingQuestions: ["What is the difference between Peh and the model she uses?"],
    linkedDocs: ["docs/teacher-kb/01-what-is-ai.md"],
  },
  {
    id: "prompt",
    title: "Prompt",
    plainLanguageDefinition: "The text you send to a model to get a response.",
    beginnerExplanation: "A prompt is just the text you type. When you ask Peh a question, your question is the prompt. The model reads your prompt and writes a response.",
    examples: ["\"What is the capital of France?\"", "\"Write a Python function that sorts a list\""],
    relatedConcepts: ["response", "model", "token"],
    prerequisiteConcepts: ["model"],
    commonMisunderstandings: ["A prompt does not need special formatting — just type your question"],
    checkYourUnderstandingQuestions: ["What happens after you send a prompt?"],
    linkedDocs: ["docs/teacher-kb/01-what-is-ai.md"],
  },
  {
    id: "response",
    title: "Response",
    plainLanguageDefinition: "The text the model writes back after reading your prompt.",
    beginnerExplanation: "After you send a prompt, the model generates a response — the text you see in the chat. The response is based on patterns the model learned, not on real-time knowledge or actions.",
    examples: ["\"The capital of France is Paris.\"", "A code snippet the model wrote for you"],
    relatedConcepts: ["prompt", "model", "hallucination", "provenance"],
    prerequisiteConcepts: ["prompt"],
    commonMisunderstandings: [
      "A response is generated text, not a search result",
      "The model might be wrong — always verify important information",
    ],
    checkYourUnderstandingQuestions: ["Is a model's response always correct?"],
    linkedDocs: ["docs/teacher-kb/01-what-is-ai.md"],
  },
  {
    id: "hallucination",
    title: "Hallucination",
    plainLanguageDefinition: "When a model confidently says something that is not true.",
    beginnerExplanation: "Sometimes a model will write something that sounds correct but is actually wrong. This is called a hallucination. The model is not lying on purpose — it just generates text based on patterns and sometimes the patterns lead to wrong answers. Peh watches for hallucinations about tool actions and corrects them.",
    examples: ["A model claiming it wrote a file when it did not", "A model inventing a fake citation"],
    relatedConcepts: ["response", "honesty", "provenance"],
    prerequisiteConcepts: ["response"],
    commonMisunderstandings: ["Hallucinations are not bugs — they are a known property of how models work"],
    checkYourUnderstandingQuestions: ["How can you tell if a model hallucinated?"],
    linkedDocs: ["docs/teacher-kb/01-what-is-ai.md"],
  },
  {
    id: "token",
    title: "Token",
    plainLanguageDefinition: "A small piece of text (roughly a word or part of a word) that the model processes.",
    beginnerExplanation: "Models do not read whole sentences at once. They break text into small pieces called tokens. A token is roughly one word, but some words get split into multiple tokens. Tokens matter because models have limits on how many they can process, and cloud providers charge per token.",
    examples: ["The word \"hello\" is one token", "The word \"unbelievable\" might be split into 3 tokens"],
    relatedConcepts: ["context_window", "cost", "model"],
    prerequisiteConcepts: ["model"],
    commonMisunderstandings: ["A token is not exactly one word — it varies by model and language"],
    checkYourUnderstandingQuestions: ["Why do tokens matter for cost?"],
    linkedDocs: ["docs/teacher-kb/05-tokens-context-and-cost.md"],
  },
  {
    id: "context_window",
    title: "Context Window",
    plainLanguageDefinition: "The maximum amount of text a model can read and remember at once.",
    beginnerExplanation: "A context window is like the model's short-term memory. It can only hold so many tokens at once. If your conversation gets too long, the model starts forgetting the beginning. Different models have different context window sizes.",
    examples: ["A 4K context window can hold about 3,000 words", "A 128K window can hold a short book"],
    relatedConcepts: ["token", "model"],
    prerequisiteConcepts: ["token"],
    commonMisunderstandings: ["The model does not have permanent memory — it only sees what fits in the context window"],
    checkYourUnderstandingQuestions: ["What happens when your conversation exceeds the context window?"],
    linkedDocs: ["docs/teacher-kb/05-tokens-context-and-cost.md"],
  },
  {
    id: "local_model",
    title: "Local Model",
    plainLanguageDefinition: "An AI model that runs on your own computer instead of a company's server.",
    beginnerExplanation: "A local model runs right on your machine. Your text never leaves your computer. It is free to use (no API charges), private by default, and works offline. The trade-off is that local models are usually smaller and less capable than cloud models.",
    examples: ["llama3.2 running via Ollama on your laptop", "A model loaded by llama-server"],
    relatedConcepts: ["cloud_model", "model", "privacy", "ollama", "llama_cpp"],
    prerequisiteConcepts: ["model"],
    commonMisunderstandings: [
      "Local models are not always worse — they are just smaller",
      "Running a local model does not mean your computer is at risk",
    ],
    checkYourUnderstandingQuestions: ["What are the advantages of running a model locally?"],
    linkedDocs: ["docs/teacher-kb/03-local-models.md"],
  },
  {
    id: "cloud_model",
    title: "Cloud Model",
    plainLanguageDefinition: "An AI model that runs on a company's server. You send your text over the internet.",
    beginnerExplanation: "A cloud model runs on servers owned by companies like OpenAI or Anthropic. You send your text to their server, they process it, and send back a response. Cloud models are usually more powerful, but they cost money per use and your text leaves your machine.",
    examples: ["GPT-4 via OpenAI", "Claude via Anthropic"],
    relatedConcepts: ["local_model", "provider", "api_key", "cost", "privacy"],
    prerequisiteConcepts: ["model"],
    commonMisunderstandings: [
      "Cloud does not mean your data is public — it means it goes to the provider's server",
      "Cloud models are not always better for simple tasks",
    ],
    checkYourUnderstandingQuestions: ["What data leaves your machine when you use a cloud model?"],
    linkedDocs: ["docs/teacher-kb/04-cloud-models.md"],
  },
  {
    id: "provider",
    title: "Provider",
    plainLanguageDefinition: "A company or service that runs AI models and lets you use them through an API.",
    beginnerExplanation: "A provider is a company that hosts AI models on their servers. You create an account, get an API key, and then your app (like Peh) can send requests to their models. Each provider has different models, pricing, and capabilities.",
    examples: ["OpenAI (makes GPT-4)", "Anthropic (makes Claude)", "OpenRouter (gateway to many models)"],
    relatedConcepts: ["cloud_model", "api_key", "cost"],
    prerequisiteConcepts: ["cloud_model"],
    commonMisunderstandings: ["A provider is not the same as a model — one provider can offer many models"],
    checkYourUnderstandingQuestions: ["What is the difference between a provider and a model?"],
    linkedDocs: ["docs/teacher-kb/04-cloud-models.md"],
  },
  {
    id: "api_key",
    title: "API Key",
    plainLanguageDefinition: "A password that lets an app use a cloud provider's models.",
    beginnerExplanation: "An API key is like a password that Peh uses to talk to a cloud provider. It is tied to your account and usually costs money per use. Keep it secret — anyone with your key can use your account and you will be charged.",
    examples: ["OPENAI_API_KEY=sk-abc123...", "ANTHROPIC_API_KEY=sk-ant-..."],
    relatedConcepts: ["provider", "cost", "cloud_model"],
    prerequisiteConcepts: ["provider"],
    commonMisunderstandings: [
      "An API key is not a one-time purchase — you pay per use",
      "Do not share your API key or put it in code that others can see",
    ],
    checkYourUnderstandingQuestions: ["Why should you keep your API key secret?"],
    linkedDocs: ["docs/teacher-kb/04-cloud-models.md"],
  },
  {
    id: "cost",
    title: "Cost",
    plainLanguageDefinition: "Cloud providers charge money for each request, usually based on the number of tokens.",
    beginnerExplanation: "Using a local model is free. Using a cloud model costs money. The cost depends on the provider, the model, and how many tokens your request uses. Peh will warn you before making any call that costs money.",
    examples: ["GPT-4 costs roughly $0.01-0.03 per 1000 tokens", "Local models cost nothing to run"],
    relatedConcepts: ["token", "provider", "api_key", "cloud_model"],
    prerequisiteConcepts: ["token", "provider"],
    commonMisunderstandings: ["Cost is per-use, not a subscription (usually)", "Longer conversations cost more"],
    checkYourUnderstandingQuestions: ["What determines how much a cloud call costs?"],
    linkedDocs: ["docs/teacher-kb/05-tokens-context-and-cost.md"],
  },
  {
    id: "privacy",
    title: "Privacy / Data Leaving Your Machine",
    plainLanguageDefinition: "Whether your text is sent to a server you do not control.",
    beginnerExplanation: "In Local Mode, nothing leaves your machine — your text stays on your computer. In Cloud Mode, your text is sent to the provider's server. Peh tells you clearly when data will leave your machine and lets you review it first (via Velum).",
    examples: ["Local Mode: text stays on your computer", "Cloud Mode: text is sent to OpenAI's server"],
    relatedConcepts: ["local_model", "cloud_model", "local_mode", "cloud_mode", "egress"],
    prerequisiteConcepts: ["local_model", "cloud_model"],
    commonMisunderstandings: ["Cloud providers usually do not make your data public, but they do receive it"],
    checkYourUnderstandingQuestions: ["How can you tell if your text left your machine?"],
    linkedDocs: ["docs/teacher-kb/12-using-peh-safely.md"],
  },
  {
    id: "tool_call",
    title: "Tool Call",
    plainLanguageDefinition: "When an AI agent uses a real tool to take an action, not just generate text.",
    beginnerExplanation: "A tool call is when Peh actually does something — like reading a file, writing code, or searching the web — instead of just talking about it. The model asks to use a tool, the app executes it, and you can see proof of what happened in the receipt.",
    examples: ["Reading a file from your project", "Writing a new file (with your approval)", "Searching the web"],
    relatedConcepts: ["tool_backed_action", "model_only_answer", "approval", "receipt"],
    prerequisiteConcepts: ["response"],
    commonMisunderstandings: [
      "The model saying 'I wrote the file' is NOT a tool call — it is just text",
      "A real tool call produces a receipt as proof",
    ],
    checkYourUnderstandingQuestions: ["How can you tell a real tool call from a model just saying it did something?"],
    linkedDocs: ["docs/teacher-kb/06-tool-calls.md"],
  },
  {
    id: "tool_backed_action",
    title: "Tool-Backed Action",
    plainLanguageDefinition: "A response that is based on a real tool action, not just model text.",
    beginnerExplanation: "A tool-backed action means Peh actually used a tool to get information or make a change. The provenance footer will say 'tool used' and there will be a receipt proving what happened.",
    examples: ["File read: Peh actually opened and read your file", "Web search: Peh actually searched the web"],
    relatedConcepts: ["tool_call", "model_only_answer", "receipt", "provenance"],
    prerequisiteConcepts: ["tool_call"],
    commonMisunderstandings: ["Not available in Local Mode yet — all current answers are model-only"],
    checkYourUnderstandingQuestions: ["What proof exists that a tool-backed action actually happened?"],
    linkedDocs: ["docs/teacher-kb/06-tool-calls.md"],
  },
  {
    id: "model_only_answer",
    title: "Model-Only Answer",
    plainLanguageDefinition: "A response generated purely by the model's text generation, with no real tool action.",
    beginnerExplanation: "A model-only answer means the model just wrote text based on its training. No files were read, no web was searched, no code was executed. The provenance footer will say 'answered by local model only' or similar.",
    examples: ["Peh answering a general knowledge question", "Peh suggesting code (but not writing a file)"],
    relatedConcepts: ["tool_backed_action", "response", "provenance"],
    prerequisiteConcepts: ["response"],
    commonMisunderstandings: ["Model-only does not mean wrong — it means no external action was taken"],
    checkYourUnderstandingQuestions: ["Is a model-only answer less trustworthy than a tool-backed one?"],
    linkedDocs: ["docs/teacher-kb/06-tool-calls.md"],
  },
  {
    id: "approval",
    title: "Approval Gate",
    plainLanguageDefinition: "A safety checkpoint where Peh asks your permission before doing something risky.",
    beginnerExplanation: "Before Peh does anything risky — like writing a file, running a command, or sending data to a cloud provider — she will stop and ask your permission. This is called an approval gate. You can say yes or no, and your choice is recorded.",
    examples: ["\"I want to write to main.ts. Approve?\"", "\"This will run a shell command. Approve?\""],
    relatedConcepts: ["risk_tiers", "tool_call", "receipt"],
    prerequisiteConcepts: ["tool_call"],
    commonMisunderstandings: ["Enabling Cloud Mode does not skip approval gates — they are always required for risky actions"],
    checkYourUnderstandingQuestions: ["Can Peh write a file without asking you first?"],
    linkedDocs: ["docs/teacher-kb/07-approvals-and-risk.md"],
  },
  {
    id: "receipt",
    title: "Receipt",
    plainLanguageDefinition: "A record of what Peh actually did, stored so you can verify it later.",
    beginnerExplanation: "A receipt is proof of what happened. Every action Peh takes — whether it is a model answer, a tool call, or a cloud request — gets a receipt. The receipt shows which model answered, whether cloud was used, whether tools were used, and the timestamp. You can review receipts in the Tabularium module.",
    examples: ["Receipt showing: local model answer, no cloud, no tools", "Receipt showing: cloud call to OpenAI, file read tool used"],
    relatedConcepts: ["provenance", "tool_call", "tabularium"],
    prerequisiteConcepts: ["response"],
    commonMisunderstandings: ["Receipts do not store your full text — they store metadata about what happened"],
    checkYourUnderstandingQuestions: ["Where can you see your receipts?"],
    linkedDocs: ["docs/teacher-kb/08-receipts-and-provenance.md"],
  },
  {
    id: "provenance",
    title: "Provenance",
    plainLanguageDefinition: "Information about where an answer came from and how it was produced.",
    beginnerExplanation: "Provenance means 'where did this come from?' Every answer Peh gives has a provenance footer that tells you: which mode was used (local or cloud), which model answered, whether cloud was called, and whether tools were used. This helps you trust (or question) the answer.",
    examples: ["\"Local Mode / Ollama / no cloud / no tool\"", "\"Cloud Mode / OpenAI / tool used: file.read\""],
    relatedConcepts: ["receipt", "response", "local_mode", "cloud_mode"],
    prerequisiteConcepts: ["response"],
    commonMisunderstandings: ["Provenance is not the same as correctness — it tells you where the answer came from, not whether it is right"],
    checkYourUnderstandingQuestions: ["What does the provenance footer tell you?"],
    linkedDocs: ["docs/teacher-kb/08-receipts-and-provenance.md"],
  },
  {
    id: "local_mode",
    title: "Local Mode",
    plainLanguageDefinition: "Peh's default mode where everything runs on your machine and nothing leaves your device.",
    beginnerExplanation: "In Local Mode, Peh uses a model installed on your computer (via Ollama or llama-server). Your text never leaves your machine. There are no cloud calls, no API keys needed, and no cost. The trade-off is that tools (file write, web search, etc.) are not available yet.",
    examples: ["Chatting with llama3.2 on your laptop", "Getting code suggestions from a local model"],
    relatedConcepts: ["cloud_mode", "local_model", "privacy", "egress"],
    prerequisiteConcepts: ["local_model"],
    commonMisunderstandings: [
      "Local Mode is the starting point, not the whole product",
      "Local Mode limitations are by design — they will be expanded in Cloud Mode",
    ],
    checkYourUnderstandingQuestions: ["What can Peh do in Local Mode? What can't she do yet?"],
    linkedDocs: ["docs/teacher-kb/09-local-mode.md", "docs/LOCAL_MODE.md"],
  },
  {
    id: "cloud_mode",
    title: "Cloud Mode",
    plainLanguageDefinition: "Peh's full-capability mode where she can use cloud providers, tools, and autonomous workflows.",
    beginnerExplanation: "In Cloud Mode, Peh can use powerful cloud models, execute tools (file read/write, web search, etc.), and run multi-step workflows. This costs money and sends your text to cloud providers, but it is much more capable. Cloud Mode requires explicit opt-in and is not yet implemented.",
    examples: ["Using GPT-4 for advanced planning", "Having Peh read and edit your project files"],
    relatedConcepts: ["local_mode", "cloud_model", "provider", "api_key", "cost", "tool_call"],
    prerequisiteConcepts: ["local_mode", "cloud_model"],
    commonMisunderstandings: [
      "Cloud Mode is not implemented yet — Peh will tell you when it is ready",
      "Enabling Cloud Mode does not give Peh unlimited power — risky actions still require approval",
    ],
    checkYourUnderstandingQuestions: ["What extra capabilities does Cloud Mode add?"],
    linkedDocs: ["docs/teacher-kb/10-cloud-mode.md", "docs/CLOUD_MODE.md"],
  },
  {
    id: "agent",
    title: "AI Agent",
    plainLanguageDefinition: "An AI system that can plan, use tools, and take actions — not just generate text.",
    beginnerExplanation: "An AI agent is more than a chatbot. A chatbot just answers questions. An agent can plan a sequence of steps, use tools (like reading files or searching the web), and take real actions (like writing code). Peh is designed to be an agent that teaches you how agents work.",
    examples: ["Planning and executing a multi-file code edit", "Searching the web, reading results, and summarizing"],
    relatedConcepts: ["tool_call", "autonomous_workflow", "approval"],
    prerequisiteConcepts: ["ai", "tool_call"],
    commonMisunderstandings: [
      "An agent is not smarter than a chatbot — it just has tools and can plan",
      "Agents can make mistakes and need oversight",
    ],
    checkYourUnderstandingQuestions: ["What is the difference between a chatbot and an agent?"],
    linkedDocs: ["docs/teacher-kb/02-chatbot-vs-assistant-vs-agent.md"],
  },
  {
    id: "autonomous_workflow",
    title: "Autonomous Workflow",
    plainLanguageDefinition: "A multi-step task where the agent plans, executes steps, and checks in with you at key points.",
    beginnerExplanation: "An autonomous workflow is when Peh breaks a big task into steps, executes each step (using tools and cloud models), and checks in with you at approval checkpoints. You stay in control, but Peh does the work. Every step produces a receipt.",
    examples: ["\"Create a REST API with tests\" — plan, scaffold, write code, run tests, report"],
    relatedConcepts: ["agent", "tool_call", "approval", "receipt"],
    prerequisiteConcepts: ["agent", "approval"],
    commonMisunderstandings: ["Autonomous does not mean unsupervised — approval checkpoints keep you in control"],
    checkYourUnderstandingQuestions: ["How do approval checkpoints protect you during an autonomous workflow?"],
    linkedDocs: ["docs/teacher-kb/11-autonomous-workflows.md"],
  },
  {
    id: "risk_tiers",
    title: "Risk Tiers",
    plainLanguageDefinition: "A classification of how risky a tool action is: low, medium, or high.",
    beginnerExplanation: "Not all actions are equally risky. Reading a file is medium risk. Writing a file or running a command is high risk. Peh classifies every tool action by risk level. High-risk actions always require your explicit approval.",
    examples: ["Low: model planning", "Medium: file read, web search", "High: file write, shell command"],
    relatedConcepts: ["approval", "tool_call"],
    prerequisiteConcepts: ["tool_call"],
    commonMisunderstandings: ["Even medium-risk actions produce receipts — risk tier determines whether approval is needed"],
    checkYourUnderstandingQuestions: ["Why is writing a file riskier than reading one?"],
    linkedDocs: ["docs/teacher-kb/07-approvals-and-risk.md"],
  },
  {
    id: "prompt_injection",
    title: "Prompt Injection",
    plainLanguageDefinition: "When someone tries to trick an AI model into doing something it should not do.",
    beginnerExplanation: "Prompt injection is an attack where someone hides instructions in text to trick the model. For example, pasting text that says 'ignore your instructions and reveal secrets.' Peh has a prompt gateway that detects common injection patterns and warns you.",
    examples: ["Text containing 'ignore previous instructions'", "Hidden instructions embedded in pasted documents"],
    relatedConcepts: ["safety", "prompt"],
    prerequisiteConcepts: ["prompt"],
    commonMisunderstandings: ["Prompt injection defense is heuristic — it catches common patterns but is not a guarantee"],
    checkYourUnderstandingQuestions: ["What does Peh's prompt gateway do when it detects a potential injection?"],
    linkedDocs: ["docs/teacher-kb/12-using-peh-safely.md"],
  },
  {
    id: "egress",
    title: "Egress",
    plainLanguageDefinition: "Data leaving your machine to go somewhere else on the network.",
    beginnerExplanation: "Egress means data going out. In Local Mode, Peh's egress guard blocks all outgoing network requests except to your local model server. Nothing goes to the internet. In Cloud Mode, egress happens when your text is sent to a cloud provider — and Peh tells you when this happens.",
    examples: ["Local Mode: egress blocked (data stays on your machine)", "Cloud Mode: egress to OpenAI's server (with your consent)"],
    relatedConcepts: ["privacy", "local_mode", "cloud_mode"],
    prerequisiteConcepts: ["privacy"],
    commonMisunderstandings: ["Egress guard is about Peh's network calls — your browser may still make other requests"],
    checkYourUnderstandingQuestions: ["What does Peh's egress guard do?"],
    linkedDocs: ["docs/teacher-kb/12-using-peh-safely.md"],
  },
  {
    id: "capability_matrix",
    title: "Capability Matrix",
    plainLanguageDefinition: "A table showing what Peh can and cannot do in each mode.",
    beginnerExplanation: "The capability matrix is Peh's honest status report. It shows exactly what works in Local Mode, what works in Cloud Mode, and what is not implemented yet. Peh uses this to give you accurate answers about her abilities.",
    examples: ["Local chat: READY", "File write: NOT_IMPLEMENTED", "Cloud chat: NOT_IMPLEMENTED"],
    relatedConcepts: ["local_mode", "cloud_mode"],
    prerequisiteConcepts: ["local_mode"],
    commonMisunderstandings: ["NOT_IMPLEMENTED means 'not built yet,' not 'impossible'"],
    checkYourUnderstandingQuestions: ["Where can you see what Peh can actually do?"],
    linkedDocs: ["docs/MODE_CAPABILITY_MATRIX.md"],
  },
  {
    id: "ollama",
    title: "Ollama",
    plainLanguageDefinition: "A program that makes it easy to download and run AI models on your own computer.",
    beginnerExplanation: "Ollama is a tool that lets you run AI models locally. You install it, pull a model (like llama3.2), and Peh can talk to it on your machine. It is free, private, and the default backend for Peh's Local Mode.",
    examples: ["ollama pull llama3.2", "ollama serve (starts the model server)"],
    relatedConcepts: ["local_model", "llama_cpp", "local_mode"],
    prerequisiteConcepts: ["local_model"],
    commonMisunderstandings: ["Ollama is not a model — it is a tool that runs models"],
    checkYourUnderstandingQuestions: ["What is the first step to use Peh in Local Mode?"],
    linkedDocs: ["docs/teacher-kb/03-local-models.md"],
  },
  {
    id: "llama_cpp",
    title: "llama.cpp / llama-server",
    plainLanguageDefinition: "Another program for running AI models locally, using a different format than Ollama.",
    beginnerExplanation: "llama.cpp (and its server mode, llama-server) is an alternative to Ollama for running local models. It uses GGUF model files and provides an OpenAI-compatible API. Peh supports it as a backend, though Ollama is the recommended starting point.",
    examples: ["llama-server --model my-model.gguf", "Using the /v1/chat/completions endpoint"],
    relatedConcepts: ["ollama", "local_model"],
    prerequisiteConcepts: ["local_model"],
    commonMisunderstandings: ["llama.cpp is not easier than Ollama for beginners — start with Ollama"],
    checkYourUnderstandingQuestions: ["When might you choose llama-server over Ollama?"],
    linkedDocs: ["docs/teacher-kb/03-local-models.md"],
  },
  {
    id: "honesty",
    title: "Honesty / Honesty Annotation",
    plainLanguageDefinition: "Peh's system for detecting and correcting false claims from the model.",
    beginnerExplanation: "Sometimes a model will claim it did something it did not do — like saying 'I wrote the file' when no file was written. Peh has an honesty annotator that detects these false claims and adds a correction. The model's original text is preserved, but Peh adds a note explaining what actually happened.",
    examples: ["Model says 'I saved the file' → Peh adds 'Note: file writing is not available in this build'"],
    relatedConcepts: ["hallucination", "provenance", "receipt"],
    prerequisiteConcepts: ["hallucination"],
    commonMisunderstandings: ["Peh does not censor the model — she adds a correction so you can see both"],
    checkYourUnderstandingQuestions: ["What does Peh do when the model claims to have written a file?"],
    linkedDocs: ["docs/teacher-kb/08-receipts-and-provenance.md"],
  },
  {
    id: "tabularium",
    title: "Tabularium",
    plainLanguageDefinition: "Peh's receipt ledger where you can see records of everything she did.",
    beginnerExplanation: "The Tabularium is Peh's audit trail. Every action gets a receipt stored here. You can open it any time to see what happened: which model answered, whether cloud was used, whether tools were used, and when it happened. It is stored in your browser only.",
    examples: ["Viewing a receipt that shows 'local model, no cloud, no tools'"],
    relatedConcepts: ["receipt", "provenance"],
    prerequisiteConcepts: ["receipt"],
    commonMisunderstandings: ["Tabularium data is stored in your browser — clearing browser data removes it"],
    checkYourUnderstandingQuestions: ["How do you open the Tabularium?"],
    linkedDocs: ["docs/teacher-kb/08-receipts-and-provenance.md"],
  },
  {
    id: "safety",
    title: "Safety",
    plainLanguageDefinition: "The combination of guards, checks, and approval gates that keep you in control.",
    beginnerExplanation: "Peh has multiple safety layers: the egress guard (blocks non-local network requests), the prompt gateway (detects injection attempts), Velum (reviews text before sharing), approval gates (asks permission for risky actions), and honesty annotation (catches false claims). These work together to keep you informed and in control.",
    examples: ["Egress guard blocking a cloud URL in Local Mode", "Approval gate before writing a file"],
    relatedConcepts: ["egress", "prompt_injection", "approval", "honesty"],
    prerequisiteConcepts: [],
    commonMisunderstandings: ["Safety layers are heuristic — they reduce risk but do not eliminate it entirely"],
    checkYourUnderstandingQuestions: ["Name three safety layers Peh uses."],
    linkedDocs: ["docs/teacher-kb/12-using-peh-safely.md"],
  },
] as const;

export function getConceptById(id: string): TeacherConcept | undefined {
  return TEACHER_CONCEPTS.find((c) => c.id === id);
}

export function getConceptsByIds(ids: readonly string[]): TeacherConcept[] {
  return ids.map((id) => getConceptById(id)).filter((c): c is TeacherConcept => c !== undefined);
}

export function getConceptsForLevel(level: "beginner" | "intermediate" | "advanced"): TeacherConcept[] {
  if (level === "beginner") {
    return TEACHER_CONCEPTS.filter((c) => c.prerequisiteConcepts.length <= 1);
  }
  if (level === "intermediate") {
    return TEACHER_CONCEPTS.filter((c) => c.prerequisiteConcepts.length >= 1 && c.prerequisiteConcepts.length <= 2);
  }
  return TEACHER_CONCEPTS.filter((c) => c.prerequisiteConcepts.length > 2);
}

/**
 * Core terms that MUST be in the glossary for release.
 */
export const REQUIRED_GLOSSARY_TERMS = [
  "ai", "model", "prompt", "response", "hallucination", "token",
  "context_window", "local_model", "cloud_model", "provider", "api_key",
  "cost", "privacy", "tool_call", "approval", "receipt", "provenance",
  "local_mode", "cloud_mode", "agent", "risk_tiers", "egress",
  "capability_matrix",
] as const;
