/**
 * Lesson registry for Peh's teaching architecture.
 *
 * Every lesson in the curriculum is registered here with its learning
 * objectives, required concepts, and the knowledge base path.
 */

import type { TeacherLesson, TeacherPath } from "./types";

export const TEACHER_LESSONS: readonly TeacherLesson[] = [
  {
    id: "what-is-ai",
    title: "What is AI?",
    level: "beginner",
    module: "ai_basics",
    objectives: [
      "Understand what AI software does",
      "Know the difference between AI and human thinking",
      "Understand what a model, prompt, and response are",
    ],
    concepts: ["ai", "model", "prompt", "response", "hallucination"],
    prerequisites: [],
    estimatedMinutes: 5,
    markdownPath: "docs/teacher-kb/01-what-is-ai.md",
    requiredForRelease: true,
    teachesPehFeature: "chat",
    userCanAsk: ["What is AI?", "What is a model?", "What is a prompt?"],
    completionCheck: "User can explain what a model does in their own words.",
  },
  {
    id: "chatbot-vs-agent",
    title: "Chatbot vs Assistant vs Agent",
    level: "beginner",
    module: "ai_basics",
    objectives: [
      "Distinguish a chatbot from an assistant from an agent",
      "Understand what makes Peh an agent (tools, planning, actions)",
    ],
    concepts: ["agent", "tool_call", "model_only_answer"],
    prerequisites: ["what-is-ai"],
    estimatedMinutes: 5,
    markdownPath: "docs/teacher-kb/02-chatbot-vs-assistant-vs-agent.md",
    requiredForRelease: true,
    userCanAsk: ["What is an agent?", "Are you a chatbot?", "What makes you different from ChatGPT?"],
    completionCheck: "User can explain the difference between a chatbot and an agent.",
  },
  {
    id: "local-models",
    title: "Local Models",
    level: "beginner",
    module: "local_mode",
    objectives: [
      "Understand what running a model locally means",
      "Know what Ollama is and how to install it",
      "Understand privacy benefits of local models",
    ],
    concepts: ["local_model", "ollama", "llama_cpp", "privacy"],
    prerequisites: ["what-is-ai"],
    estimatedMinutes: 8,
    markdownPath: "docs/teacher-kb/03-local-models.md",
    requiredForRelease: true,
    teachesPehFeature: "local_mode",
    userCanAsk: ["What is Ollama?", "What is a local model?", "Is my data private?"],
    completionCheck: "User has Ollama installed and a model pulled.",
  },
  {
    id: "cloud-models",
    title: "Cloud Models and Providers",
    level: "beginner",
    module: "cloud_mode",
    objectives: [
      "Understand what cloud models are",
      "Know what a provider and API key are",
      "Understand cost and privacy trade-offs",
    ],
    concepts: ["cloud_model", "provider", "api_key", "cost", "privacy"],
    prerequisites: ["local-models"],
    estimatedMinutes: 8,
    markdownPath: "docs/teacher-kb/04-cloud-models.md",
    requiredForRelease: true,
    teachesPehFeature: "cloud_mode",
    userCanAsk: ["What is a cloud model?", "What is an API key?", "How much does it cost?"],
    completionCheck: "User can explain the difference between local and cloud models.",
  },
  {
    id: "tokens-context-cost",
    title: "Tokens, Context Windows, and Cost",
    level: "beginner",
    module: "ai_basics",
    objectives: [
      "Understand what tokens are",
      "Understand context window limits",
      "Understand how cost relates to tokens",
    ],
    concepts: ["token", "context_window", "cost"],
    prerequisites: ["cloud-models"],
    estimatedMinutes: 5,
    markdownPath: "docs/teacher-kb/05-tokens-context-and-cost.md",
    requiredForRelease: true,
    userCanAsk: ["What is a token?", "What is a context window?", "Why does this cost money?"],
    completionCheck: "User can explain why longer conversations cost more.",
  },
  {
    id: "tool-calls",
    title: "Tool Calls",
    level: "beginner",
    module: "tools",
    objectives: [
      "Understand the difference between model text and tool actions",
      "Know what a tool-backed action is",
      "Understand how Peh catches hallucinated tool claims",
    ],
    concepts: ["tool_call", "tool_backed_action", "model_only_answer", "honesty"],
    prerequisites: ["chatbot-vs-agent"],
    estimatedMinutes: 8,
    markdownPath: "docs/teacher-kb/06-tool-calls.md",
    requiredForRelease: true,
    teachesPehFeature: "tools",
    userCanAsk: ["What is a tool call?", "Can you write files?", "How do I know you actually did something?"],
    completionCheck: "User can distinguish model text from a real tool action.",
  },
  {
    id: "approvals-and-risk",
    title: "Approvals and Risk",
    level: "beginner",
    module: "approvals",
    objectives: [
      "Understand risk tiers (low, medium, high)",
      "Know what an approval gate is",
      "Understand that Cloud Mode does not bypass approvals",
    ],
    concepts: ["approval", "risk_tiers"],
    prerequisites: ["tool-calls"],
    estimatedMinutes: 5,
    markdownPath: "docs/teacher-kb/07-approvals-and-risk.md",
    requiredForRelease: true,
    teachesPehFeature: "approvals",
    userCanAsk: ["What is an approval gate?", "What actions are risky?", "Can you do things without asking?"],
    completionCheck: "User can explain why file writing requires approval.",
  },
  {
    id: "receipts-and-provenance",
    title: "Receipts and Provenance",
    level: "beginner",
    module: "receipts",
    objectives: [
      "Understand what a receipt proves",
      "Read a provenance footer",
      "Find and read receipts in ActivityLog",
    ],
    concepts: ["receipt", "provenance", "activity-log"],
    prerequisites: ["tool-calls"],
    estimatedMinutes: 5,
    markdownPath: "docs/teacher-kb/08-receipts-and-provenance.md",
    requiredForRelease: true,
    teachesPehFeature: "receipts",
    userCanAsk: ["What is a receipt?", "What does the footer mean?", "How do I know what you did?"],
    completionCheck: "User can find and read a receipt in ActivityLog.",
  },
  {
    id: "local-mode",
    title: "Local Mode in Depth",
    level: "beginner",
    module: "local_mode",
    objectives: [
      "Understand everything Local Mode can do",
      "Understand Local Mode limitations and why they exist",
      "Know that API keys do not change Local Mode",
    ],
    concepts: ["local_mode", "egress", "capability_matrix"],
    prerequisites: ["local-models", "receipts-and-provenance"],
    estimatedMinutes: 5,
    markdownPath: "docs/teacher-kb/09-local-mode.md",
    requiredForRelease: true,
    teachesPehFeature: "local_mode",
    userCanAsk: ["What can you do in Local Mode?", "Why can't you write files?", "What is the egress guard?"],
    completionCheck: "User can list three things Local Mode can do and three it cannot.",
  },
  {
    id: "cloud-mode",
    title: "Cloud Mode in Depth",
    level: "intermediate",
    module: "cloud_mode",
    objectives: [
      "Understand what Cloud Mode adds",
      "Know how to enable Cloud Mode safely",
      "Understand the consent model",
    ],
    concepts: ["cloud_mode", "provider", "api_key", "cost"],
    prerequisites: ["local-mode", "cloud-models"],
    estimatedMinutes: 8,
    markdownPath: "docs/teacher-kb/10-cloud-mode.md",
    requiredForRelease: true,
    teachesPehFeature: "cloud_mode",
    userCanAsk: ["How do I enable Cloud Mode?", "What does Cloud Mode add?", "Is Cloud Mode safe?"],
    completionCheck: "User can explain the steps to safely enable Cloud Mode.",
  },
  {
    id: "autonomous-workflows",
    title: "Autonomous Workflows",
    level: "intermediate",
    module: "autonomous_agents",
    objectives: [
      "Understand multi-step agent workflows",
      "Know what approval checkpoints are",
      "Understand the audit trail of an autonomous task",
    ],
    concepts: ["autonomous_workflow", "agent", "approval", "receipt"],
    prerequisites: ["cloud-mode", "approvals-and-risk"],
    estimatedMinutes: 10,
    markdownPath: "docs/teacher-kb/11-autonomous-workflows.md",
    requiredForRelease: true,
    teachesPehFeature: "autonomous_workflows",
    userCanAsk: ["Can you do multi-step tasks?", "How do autonomous workflows work?", "What are approval checkpoints?"],
    completionCheck: "User can describe what happens at each stage of an autonomous workflow.",
  },
  {
    id: "using-peh-safely",
    title: "Using Peh Safely",
    level: "beginner",
    module: "safety",
    objectives: [
      "Understand Peh's safety layers",
      "Know how to verify what Peh did",
      "Understand prompt injection risks",
    ],
    concepts: ["safety", "prompt_injection", "egress", "honesty"],
    prerequisites: ["receipts-and-provenance"],
    estimatedMinutes: 5,
    markdownPath: "docs/teacher-kb/12-using-peh-safely.md",
    requiredForRelease: true,
    teachesPehFeature: "safety",
    userCanAsk: ["Is Peh safe?", "What is prompt injection?", "How do I verify what you did?"],
    completionCheck: "User can name three safety layers and explain what each does.",
  },
  {
    id: "common-questions",
    title: "Common Beginner Questions",
    level: "beginner",
    module: "ai_basics",
    objectives: ["Get quick answers to the most common beginner questions"],
    concepts: ["ai", "local_mode", "cloud_mode", "tool_call", "receipt"],
    prerequisites: [],
    estimatedMinutes: 5,
    markdownPath: "docs/teacher-kb/13-common-beginner-questions.md",
    requiredForRelease: true,
    userCanAsk: ["What are you?", "What can you do?", "What can't you do?"],
    completionCheck: "User can answer basic questions about Peh.",
  },
  {
    id: "glossary",
    title: "Glossary",
    level: "beginner",
    module: "ai_basics",
    objectives: ["Look up any term quickly"],
    concepts: [],
    prerequisites: [],
    estimatedMinutes: 0,
    markdownPath: "docs/teacher-kb/14-glossary.md",
    requiredForRelease: true,
    userCanAsk: ["What does this word mean?"],
    completionCheck: "Reference material — no completion check.",
  },
] as const;

export const TEACHER_PATHS: readonly TeacherPath[] = [
  {
    id: "beginner-to-agent",
    title: "From Beginner to Agent User",
    description: "The complete learning path from zero AI experience to confident agent user.",
    targetAudience: "Someone who has never used an AI tool before.",
    lessons: [
      "what-is-ai",
      "chatbot-vs-agent",
      "local-models",
      "cloud-models",
      "tokens-context-cost",
      "tool-calls",
      "approvals-and-risk",
      "receipts-and-provenance",
      "local-mode",
      "cloud-mode",
      "autonomous-workflows",
      "using-peh-safely",
    ],
    graduationCriteria: "User can explain local vs cloud mode, use tools with approval, read receipts, and run an autonomous workflow with confidence.",
  },
  {
    id: "local-quick-start",
    title: "Local Mode Quick Start",
    description: "Get chatting locally as fast as possible.",
    targetAudience: "Someone who just wants to try local chat.",
    lessons: [
      "what-is-ai",
      "local-models",
      "local-mode",
      "receipts-and-provenance",
    ],
    graduationCriteria: "User can run a local chat and understand the provenance footer.",
  },
] as const;

export function getLessonById(id: string): TeacherLesson | undefined {
  return TEACHER_LESSONS.find((l) => l.id === id);
}

export function getLessonsByModule(module: string): TeacherLesson[] {
  return TEACHER_LESSONS.filter((l) => l.module === module);
}

export function getRequiredLessons(): TeacherLesson[] {
  return TEACHER_LESSONS.filter((l) => l.requiredForRelease);
}

export function getPathById(id: string): TeacherPath | undefined {
  return TEACHER_PATHS.find((p) => p.id === id);
}
